Seaboard.Intranet.Web/Controllers/ARController.cs
using Microsoft.AspNet.Identity;
using Seaboard.Intranet.BusinessLogic;
using Seaboard.Intranet.Data;
using Seaboard.Intranet.Domain;
using Seaboard.Intranet.Domain.Models;
using Seaboard.Intranet.Domain.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Seaboard.Intranet.Data.Repository;

namespace Seaboard.Intranet.Web.Controllers
{
    [Authorize]
    public class ArController : Controller
    {
        private readonly GenericRepository _repository;

        public ArController()
        {
            var db = new SeaboContext();
            _repository = new GenericRepository(db);
        }

        public ActionResult Index()
        {
            if (!HelperLogic.GetPermission(Account.GetAccount(User.Identity.GetUserName()).UserId, "AR", "Index"))
                return RedirectToAction("NotPermission", "Home");

            string sqlQuery = "SELECT DISTINCT LTRIM(RTRIM(A.PROYCTID)) ProjectId, RTRIM(A.PROYCTDS) ProjectDesc, RTRIM(A.ACCNTNUM) AccountNum "
                    + "FROM " + Helpers.InterCompanyId + ".dbo.LPPOP40200 A "
                    + "INNER JOIN " + Helpers.InterCompanyId + ".dbo.LPPOP40400 B "
                    + "ON A.PROYCTID = B.PROYCTID "
                    + "WHERE LOWER(RTRIM(B.DEPRTMID)) = LOWER(RTRIM('" + Account.GetAccount(User.Identity.GetUserName()).Department + "')) ";

            var projects = _repository.ExecuteQuery<Project>(sqlQuery);
            foreach (var item in projects)
            {
                sqlQuery = "SELECT DISTINCT RTRIM(ARNUMBER) ARNumber, RTRIM(ARDESC) ARDescription, RTRIM(ACCNTNUM) AccountNum, "
                   + "RTRIM(DEPRTMID) DepartmentId, DOCAMNT Amount "
                   + "FROM " + Helpers.InterCompanyId + ".dbo.LPPOP40400 "
                   + "WHERE PROYCTID = '" + item.ProjectId + "'";
                item.ProjectLines = _repository.ExecuteQuery<Ar>(sqlQuery).ToList();
            }
            return View(projects);
        }

        public ActionResult Create()
        {
            if (!HelperLogic.GetPermission(Account.GetAccount(User.Identity.GetUserName()).UserId, "AR", "Index"))
                return RedirectToAction("NotPermission", "Home");
            ViewBag.DepartmentId = Account.GetAccount(User.Identity.GetUserName()).Department;
            return View();
        }

        public ActionResult Edit(string id)
        {
            if (!HelperLogic.GetPermission(Account.GetAccount(User.Identity.GetUserName()).UserId, "AR", "Index"))
                return RedirectToAction("NotPermission", "Home");

            string sqlQuery = "SELECT DISTINCT LTRIM(RTRIM(PROYCTID)) ProjectId, PROYCTDS ProjectDesc, RTRIM(ACCNTNUM) AccountNum "
                    + "FROM " + Helpers.InterCompanyId + ".dbo.LPPOP40200 "
                    + "WHERE RTRIM(PROYCTID) = RTRIM('" + id + "')";

            var project = _repository.ExecuteScalarQuery<Project>(sqlQuery);

            if (project != null)
            {
                sqlQuery = "SELECT DISTINCT RTRIM(ARNUMBER) ARNumber, RTRIM(ARDESC) ARDescription, RTRIM(ACCNTNUM) AccountNum, "
                   + "RTRIM(DEPRTMID) DepartmentId, DOCAMNT Amount "
                   + "FROM " + Helpers.InterCompanyId + ".dbo.LPPOP40400 "
                   + "WHERE PROYCTID = '" + project.ProjectId + "'";

                project.ProjectLines = _repository.ExecuteQuery<Ar>(sqlQuery).ToList();
            }

            ViewBag.DepartmentId = project.ProjectLines.First().DepartmentId;
            return View(project);
        }

        public ActionResult Inquiry()
        {
            if (!HelperLogic.GetPermission(Account.GetAccount(User.Identity.GetUserName()).UserId, "AR", "Inquiry"))
                return RedirectToAction("NotPermission", "Home");

            string sqlQuery = "SELECT DISTINCT RTRIM(ARNUMBER) ARNumber, RTRIM(ARDESC) ARDescription, RTRIM(ACCNTNUM) AccountNum, "
                   + "RTRIM(DEPRTMID) DepartmentId, DOCAMNT Amount "
                   + "FROM " + Helpers.InterCompanyId + ".dbo.LPPOP40400 "
                   + "WHERE DEPRTMID = '" + Account.GetAccount(User.Identity.GetUserName()).Department + "'";

            var ar = _repository.ExecuteQuery<Ar>(sqlQuery);

            foreach (var item in ar)
            {
                sqlQuery = "SELECT TOP 1 LTRIM(RTRIM(A.PROYCTID)) ProjectId, A.PROYCTDS ProjectDesc, RTRIM(A.ACCNTNUM) AccountNum "
                    + "FROM " + Helpers.InterCompanyId + ".dbo.LPPOP40200 A "
                    + "INNER JOIN " + Helpers.InterCompanyId + ".dbo.LPPOP40400 B "
                    + "ON A.PROYCTID = B.PROYCTID "
                    + "WHERE LOWER(RTRIM(B.ARNUMBER)) = LOWER(RTRIM('" + item.ArNumber + "'))";
                item.Project = _repository.ExecuteScalarQuery<Project>(sqlQuery);
                if (item.Project == null)
                    item.Project = new Project();
            }

            return View(ar);
        }

        public ActionResult Details(string id)
        {
            string sqlQuery = "SELECT DISTINCT RTRIM(ARNUMBER) ARNumber, RTRIM(ARDESC) ARDescription, RTRIM(ACCNTNUM) AccountNum, "
                   + "RTRIM(DEPRTMID) DepartmentId, DOCAMNT Amount, PROYCTID ProjectId, CREATDDT CreatedDate, MODIFDTE ModifiedDate, "
                   + "LSTUSRID CreatedBy "
                   + "FROM " + Helpers.InterCompanyId + ".dbo.LPPOP40400 "
                   + "WHERE ARNUMBER = '" + id + "'";

            List<ArPurchaseRequest> requestAr = new List<ArPurchaseRequest>();

            var ar = _repository.ExecuteScalarQuery<ArViewModel>(sqlQuery);

            if (ar != null)
            {
                sqlQuery = "SELECT DISTINCT A.POPRequisitionNumber RequestId, A.DOCDATE RequestDocumentDate, ISNULL(E.PONUMBER, '') PurchaseOrder, "
                    + "(ISNULL(E.SUBTOTAL, 0) + ISNULL(E.FRTAMNT, 0) + ISNULL(E.MSCCHAMT, 0) + ISNULL(E.TAXAMNT, 0) - ISNULL(E.TRDISAMT, 0)) Amount, "
                    + "ISNULL(E.DOCDATE, '1900-01-01') PurchaseDocumentDate "
                    + "FROM "
                    + "(SELECT POPRequisitionNumber, DOCDATE FROM " + Helpers.InterCompanyId + ".dbo.POP10200 "
                    + "UNION ALL "
                    + "SELECT POPRequisitionNumber, DOCDATE FROM " + Helpers.InterCompanyId + ".dbo.POP30200 WHERE VOIDED = 0) A "
                    + "INNER JOIN " + Helpers.InterCompanyId + ".dbo.LPRFQ10100 B "
                    + "ON A.POPRequisitionNumber = B.RFQNMBR AND B.TYPE = 3 "
                    + "LEFT JOIN " + Helpers.InterCompanyId + ".dbo.LPPOP30102 D "
                    + "ON A.POPRequisitionNumber = D.PURCHREQ "
                    + "LEFT JOIN " + Helpers.InterCompanyId + ".dbo.POP10100 E "
                    + "ON D.PONUMBE = E.PONUMBER AND E.POSTATUS <> 2 "
                    + "WHERE B.TXTFIELD = '" + ar.ArNumber + "'";

                ar.PurchaseList = _repository.ExecuteQuery<ArPurchaseRequest>(sqlQuery).ToList();

                if (ar.PurchaseList == null)
                    ar.PurchaseList = new List<ArPurchaseRequest>();
            }

            return View(ar);
        }

        [HttpPost]
        public JsonResult SaveProject(Project project)
        {
            bool status = false;

            try
            {
                if (project != null)
                {
                    _repository.ExecuteCommand(String.Format("LODYNDEV.dbo.LPPOP40200SI '{0}','{1}','{2}','{3}','{4}','{5}'",
                        Helpers.InterCompanyId, project.ProjectId, project.ProjectDesc, 0, project.ProjectLines.First().AccountNum, Account.GetAccount(User.Identity.GetUserName()).UserId));

                    _repository.ExecuteCommand(String.Format("DELETE FROM " + Helpers.InterCompanyId + ".dbo.LPPOP40400 WHERE PROYCTID = '{0}'", project.ProjectId));
                    foreach (var item in project.ProjectLines)
                        _repository.ExecuteCommand(String.Format("LODYNDEV.dbo.LPPOP40400SI '{0}','{1}','{2}','{3}','{4}','{5}','{6}','{7}','{8}'",
                          Helpers.InterCompanyId, item.ArNumber, item.ArDescription, 0, item.Amount, project.ProjectId, item.AccountNum, item.DepartmentId, Account.GetAccount(User.Identity.GetUserName()).UserId));
                }

                status = true;
            }
            catch
            {
                status = false;
            }

            return new JsonResult { Data = new { status } };
        }

        public ActionResult Project()
        {
            if (!HelperLogic.GetPermission(Account.GetAccount(User.Identity.GetUserName()).UserId, "AR", "Project"))
                return RedirectToAction("NotPermission", "Home");

            string sqlQuery = "SELECT DISTINCT LTRIM(RTRIM(A.PROYCTID)) ProjectId, RTRIM(A.PROYCTDS) ProjectDesc, RTRIM(A.ACCNTNUM) AccountNum "
                    + "FROM " + Helpers.InterCompanyId + ".dbo.LPPOP40200 A "
                    + "INNER JOIN " + Helpers.InterCompanyId + ".dbo.LPPOP40400 B "
                    + "ON A.PROYCTID = B.PROYCTID "
                    + "WHERE LOWER(RTRIM(B.DEPRTMID)) = LOWER(RTRIM('" + Account.GetAccount(User.Identity.GetUserName()).Department + "')) ";

            var projects = _repository.ExecuteQuery<Project>(sqlQuery);
            foreach (var item in projects)
            {
                sqlQuery = "SELECT DISTINCT RTRIM(ARNUMBER) ARNumber, RTRIM(ARDESC) ARDescription, RTRIM(ACCNTNUM) AccountNum, "
                   + "RTRIM(DEPRTMID) DepartmentId, DOCAMNT Amount "
                   + "FROM " + Helpers.InterCompanyId + ".dbo.LPPOP40400 "
                   + "WHERE PROYCTID = '" + item.ProjectId + "'";

                item.ProjectLines = _repository.ExecuteQuery<Ar>(sqlQuery).ToList();
            }

            return View(projects);
        }

        public ActionResult AR_Consult()
        {
            if (!HelperLogic.GetPermission(Account.GetAccount(User.Identity.GetUserName()).UserId, "AR", "Project"))

Seaboard.Intranet.Web/Views/ServiceRequest/Delete.cshtml
@model Seaboard.Intranet.Domain.Models.PurchaseRequest

<div id="modal-container" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Anular</h4>
                <h3>Esta seguro que desea anular este registro?</h3>
            </div>

            <div class="modal-body">
                <h4>Solicitud de servicio</h4>
                <hr />
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayName("Id de requisicion")
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.PurchaseRequestId)
                    </dd>

                    <dt>
                        @Html.DisplayName("Descripción")
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Description)
                    </dd>

                    <dt>
                        @Html.DisplayName("Departamento")
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.DepartmentId)
                    </dd>

                    <dt>
                        @Html.DisplayName("Solicitado por")
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Requester)
                    </dd>
                </dl>
            </div>

            <div class="modal-footer">
                @using (Html.BeginForm("Delete", "ServiceRequest", FormMethod.Post))
                {
                    @Html.HiddenFor(model => model.PurchaseRequestId)
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <input type="submit" value="Anular" class="btn btn-default" />
                    </div>
                }
            </div>
        </div>
    </div>
</div>

Seaboard.Intranet.Web/Views/ServiceRequest/Details.cshtml
@{
    Seaboard.Intranet.Domain.ViewModels.PurchaseRequestAdditionalInfoViewModel info = ViewBag.AdditionalInformation;
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel">Detalles de requisicion</h4>
</div>

<div class="modal-body">
    <div class="row">
        <div class="col-lg-12">
            <div class="tabs-container">
                <ul class="nav nav-tabs">
                    <li class="active"><a data-toggle="tab" href="#tab-1"> Detalles</a></li>
                    <li class=""><a data-toggle="tab" href="#tab-2"> Inf. add.</a></li>
                    <li class=""><a data-toggle="tab" href="#tab-3"> Inf. seg.</a></li>
                    <li class=""><a data-toggle="tab" href="#tab-4"> Analisis</a></li>
                    <li class=""><a data-toggle="tab" href="#tab-5"> Ord. compras</a></li>
                </ul>
                <div class="tab-content">
                    <div id="tab-1" class="tab-pane active">
                        <div class="panel-body">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>Id. de articulo</th>
                                        <th>Descripción</th>
                                        <th>Cantidad</th>
                                        <th>Estado</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (ViewBag.RequestDetail != null)
                                    {
                                        foreach (Seaboard.Intranet.Domain.ViewModels.PurchaseRequestLineViewModel item in ViewBag.RequestDetail)
                                        {
                                            <tr>
                                                <td>@item.ItemId.Trim()</td>
                                                <td>@item.ItemDesc.Trim()</td>
                                                <td>@item.Quantity.ToString("N2")</td>
                                                <td>@item.Status.Trim()</td>
                                            </tr>
                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>

                    <div id="tab-2" class="tab-pane">
                        <div class="panel-body">
                            <h4>Informacion adicional</h4>
                            @if (info != null)
                            {
                                <dl class="dl-horizontal">
                                    <dt>@Html.DisplayName("Descripción")</dt>
                                    <dd>@info.Description.Trim()</dd>
                                    <dt>@Html.DisplayName("Fecha requerida")</dt>
                                    <dd>@info.RequiredDate.ToString("dd/MM/yyyy")</dd>
                                    <dt>@Html.DisplayName("Fecha documento")</dt>
                                    <dd>@info.DocumentDate.ToString("dd/MM/yyyy")</dd>
                                    <dt>@Html.DisplayName("Departamento")</dt>
                                    <dd>@info.Department.Trim()</dd>
                                    <dt>@Html.DisplayName("Solicitante")</dt>
                                    <dd>@info.Requester.Trim()</dd>
                                    <dt>@Html.DisplayName("Aprobador")</dt>
                                    <dd>@info.Aprover.Trim()</dd>
                                </dl>
                            }
                        </div>
                    </div>

                    <div id="tab-3" class="tab-pane">
                        <div class="panel-body">
                            <h4>Inf. seguimiento</h4>
                            @if (info != null)
                            {
                                <dl class="dl-horizontal">
                                    <dt>@Html.DisplayName("Prep Sol de cotiz")</dt>
                                    <dd>@info.UserQuote.Trim()</dd>
                                    <dt>@Html.DisplayName("Prep Pre-Analisis")</dt>
                                    <dd>@info.UserPreAnalysis.Trim()</dd>
                                    <dt>@Html.DisplayName("Prep. Analisis")</dt>
                                    <dd>@info.UserAnalysis.Trim()</dd>
                                    <dt>@Html.DisplayName("Fecha ini sol de Cotiz")</dt>
                                    <dd>@info.QuoteDate.ToString("dd/MM/yyyy")</dd>
                                    <dt>@Html.DisplayName("Fecha ini Pre-Analisis")</dt>
                                    <dd>@info.PreAnalysisDate.ToString("dd/MM/yyyy")</dd>
                                    <dt>@Html.DisplayName("Fecha ini Analisis")</dt>
                                    <dd>@info.AnalysisDate.ToString("dd/MM/yyyy")</dd>
                                </dl>
                            }
                        </div>
                    </div>

                    <div id="tab-4" class="tab-pane">
                        <div class="panel-body">
                            <h4>Analisis</h4>
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>Id. de analisis</th>
                                        <th>Descripción</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (ViewBag.AnalysisDetail != null)
                                    {
                                        foreach (Seaboard.Intranet.Domain.ViewModels.GenericViewModel item in ViewBag.AnalysisDetail)
                                        {
                                            <tr>
                                                <td>@item.ViewDataId.Trim()</td>
                                                <td>@item.ViewDataDescription.Trim()</td>
                                            </tr>
                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>

                    <div id="tab-5" class="tab-pane">
                        <div class="panel-body">
                            <h4>Ord. de compras</h4>
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>Orden de compra</th>
                                        <th>Id. de analisis</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (ViewBag.PurchaseOrderDetail != null)
                                    {
                                        foreach (Seaboard.Intranet.Domain.ViewModels.GenericViewModel item in ViewBag.PurchaseOrderDetail)
                                        {
                                            <tr>
                                                <td>@item.ViewDataId.Trim()</td>
                                                <td>@item.ViewDataDescription.Trim()</td>
                                            </tr>
                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal" aria-hidden="true">Cerrar</button>
</div>

Seaboard.Intranet.Web/Views/ServiceRequest/_List.cshtml
@model IEnumerable<Seaboard.Intranet.Domain.ViewModels.PurchaseRequestViewModel>

<table class="table table-striped table-bordered table-hover informationTable" id="documentTable">
    <thead>
        <tr>
            <th style="width:15%">Solicitud</th>
            <th style="width:25%">Descripción</th>
            <th style="width:10%">Prioridad</th>
            <th style="width:12%">Fecha doc</th>
            <th style="width:12%">Fecha req</th>
            <th style="width:5%">Solicitante</th>
            <th style="width:10%">AR</th>
            <th style="width:8%">Estado</th>
            <th style="width:30%">#</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.ActionLink(item.RequestId, "Edit", new { id = @item.RequestId })</td>
                <td>@item.Description</td>
                <td class="text-center">
                    @switch (item.Priority.ToLower())
                    {
                        case "baja":
                            <span class="label label-success">Baja</span>
                            break;
                        case "normal":
                            <span class="label label-warning">Normal</span>
                            break;
                        case "alta":
                            <span class="label label-danger">Alta</span>
                            break;
                        default:
                            <span class="label label-success">Baja</span>
                            break;
                    }
                </td>
                <td>@item.DocumentDate.ToShortDateString()</td>
                <td>@item.RequiredDate.ToShortDateString()</td>
                <td>@item.Requester</td>
                <td>
                    @if (!String.IsNullOrEmpty(item.Ar))
                    {
                        if (item.Ar.Trim().ToUpper() == "NO")
                        {
                            @item.Ar;
                        }
                        else
                        {
                            @Html.ActionLink(item.Ar, "Details", "Ar", new { @id = item.Ar }, null)
                            ;
                        }
                    }
                    else
                    {
                        @item.Ar;
                    }
                </td>
                <td>
                    @switch (item.Status)
                    {
                        case "No enviado":
                            <i class="badge badge-danger">@item.Status</i>
                            break;
                        case "Enviado":
                            <i class="badge badge-primary">@item.Status</i>
                            break;
                        case "Rechazado":
                            <i class="badge badge-info">@item.Status</i>
                            break;
                        case "Anulado":
                            <i class="badge badge-warning">@item.Status</i>
                            break;
                        case "Aprobado":
                            <i class="badge badge-success">@item.Status</i>
                            break;
                        case "No iniciado":
                            <i class="badge badge-danger">@item.Status</i>
                            break;
                        case "En requisicion":
                            <i class="badge badge-warning-light">@item.Status</i>
                            break;
                        case "En pre-analisis":
                            <i class="badge badge-primary">@item.Status</i>
                            break;
                        case "En cotizacion":
                            <i class="badge badge-warning">@item.Status</i>
                            break;
                        case "En analisis":
                            <i class="badge badge-info">@item.Status</i>
                            break;
                        case "En compras":
                            <i class="badge badge-success">@item.Status</i>
                            break;
                        case "Recibido":
                            <i class="badge badge-success">@item.Status</i>
                            break;
                    }
                </td>
                <td>
                    <div class="btn-group">
                        <a href="@Url.Action("Details","ServiceRequest", new { id = item.RequestId })" class="modal-link"><i class="fa fa-bars"></i></a>
                        <a onclick="Print('@item.RequestId');"><i class="fa fa-print"></i></a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

Seaboard.Intranet.Web/Views/ServiceRequest/_ListWarehouse.cshtml
@model IEnumerable<Seaboard.Intranet.Domain.ViewModels.PurchaseRequestViewModel>

<table class="table table-striped table-bordered table-hover informationTable" id="documentTable">
    <thead>
        <tr>
            <th style="width:15%">Solicitud</th>
            <th style="width:15%">Sol. Original</th>
            <th style="width:25%">Descripción</th>
            <th style="width:10%">Prioridad</th>
            <th style="width:12%">Fecha doc</th>
            <th style="width:12%">Fecha req</th>
            <th style="width:5%">Solicitante</th>
            <th style="width:10%">AR</th>
            <th style="width:8%">Estado</th>
            <th style="width:30%">#</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.ActionLink(item.RequestId, "Edit", new { id = @item.RequestId })</td>
                <td>@item.OriginalRequest</td>
                <td>@item.Description</td>
                <td class="text-center">
                    @switch (item.Priority.ToLower())
                    {
                        case "baja":
                            <span class="label label-success">Baja</span>
                            break;
                        case "normal":
                            <span class="label label-warning">Normal</span>
                            break;
                        case "alta":
                            <span class="label label-danger">Alta</span>
                            break;
                        default:
                            <span class="label label-success">Baja</span>
                            break;
                    }
                </td>
                <td>@item.DocumentDate.ToShortDateString()</td>
                <td>@item.RequiredDate.ToShortDateString()</td>
                <td>@item.Requester</td>
                <td>
                    @if (!String.IsNullOrEmpty(item.Ar))
                    {
                        if (item.Ar.Trim().ToUpper() == "NO")
                        {
                            @item.Ar;
                        }
                        else
                        {
                            @Html.ActionLink(item.Ar, "Details", "Ar", new { @id = item.Ar }, null)
                            ;
                        }
                    }
                    else
                    {
                        @item.Ar;
                    }
                </td>
                <td>
                    @switch (item.Status)
                    {
                        case "No enviado":
                            <i class="badge badge-danger">@item.Status</i>
                            break;
                        case "Enviado":
                            <i class="badge badge-primary">@item.Status</i>
                            break;
                        case "Rechazado":
                            <i class="badge badge-info">@item.Status</i>
                            break;
                        case "Anulado":
                            <i class="badge badge-warning">@item.Status</i>
                            break;
                        case "Aprobado":
                            <i class="badge badge-success">@item.Status</i>
                            break;
                        case "No iniciado":
                            <i class="badge badge-danger">@item.Status</i>
                            break;
                        case "En requisicion":
                            <i class="badge badge-warning-light">@item.Status</i>
                            break;
                        case "En pre-analisis":
                            <i class="badge badge-primary">@item.Status</i>
                            break;
                        case "En cotizacion":
                            <i class="badge badge-warning">@item.Status</i>
                            break;
                        case "En analisis":
                            <i class="badge badge-info">@item.Status</i>
                            break;
                        case "En compras":
                            <i class="badge badge-success">@item.Status</i>
                            break;
                        case "Recibido":
                            <i class="badge badge-success">@item.Status</i>
                            break;
                    }
                </td>
                <td>
                    <div class="btn-group">
                        <a href="@Url.Action("Details","ServiceRequest", new { id = item.RequestId })" class="modal-link"><i class="fa fa-bars"></i></a>
                        <a onclick="Print('@item.RequestId');"><i class="fa fa-print"></i></a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>